import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default defineConfig({
  shortcuts: [],
  safelist: [
    ...[
      'i-twemoji-blue-book',
      'i-twemoji-books',
      'i-twemoji-rocket',
      'i-logos-markdown',
      'i-ep-menu',
      'i-carbon-tool-box',
      'i-carbon-character-whole-number',
      'i-carbon-map',
      'i-carbon-document-pdf',
      'i-carbon-language',
      'i-carbon-cross-tab',
      'i-carbon-move',
      'i-ep-edit-pen',
      'i-carbon-row-insert',
      'i-carbon-star-review',
      'i-ep-magic-stick',
      'i-carbon-face-satisfied',
      'i-carbon:select-window',
    ],
    ...[ // 自行新增的 icon 在這邊定義後才可在其他頁面使用 https://icon-sets.iconify.design/
      'i-carbon:user',
      'i-carbon:search',
      'i-carbon:reset',
      'i-carbon:edit',
      'i-carbon:delete',
      'i-carbon:shopping-cart',
      'i-carbon:cloud-service-management',
      'i-carbon:train',
      'i-carbon:copy',
      'i-carbon:connection-receive',
      'i-carbon:arrow-right',
      'i-carbon:airline-rapid-board',
      'i-carbon:cloud-service-management',
      'i-carbon:account',
      'i-carbon:file-storage',
      'i-carbon:time',
      'i-carbon:face-dizzy',
      'i-carbon:settings-edit',
      'i-carbon:train',
      'i-carbon:cloud-service-management',
      'i-carbon:license-maintenance',
      'i-carbon:construction',
      'i-carbon:chemistry',
      'i-carbon:user-multiple',
      'i-carbon:currency',
    ],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
    }),
    presetTypography(),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
})
